# 运算操作-2

In [1]:
import torch

In [2]:
a = torch.rand(2, 2)
a = a * 10
a

tensor([[3.3928, 5.4209],
        [9.6331, 2.7498]])

In [3]:
torch.floor(a)

tensor([[3., 5.],
        [9., 2.]])

In [4]:
torch.ceil(a)

tensor([[ 4.,  6.],
        [10.,  3.]])

In [5]:
torch.round(a)

tensor([[ 3.,  5.],
        [10.,  3.]])

In [6]:
torch.trunc(a)

tensor([[3., 5.],
        [9., 2.]])

In [9]:
torch.frac(a)

tensor([[0.3928, 0.4209],
        [0.6331, 0.7498]])