In [1]:
import torch

In [2]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [3]:
a, b

(tensor([[0.6233, 0.7911, 0.8379],
         [0.3676, 0.6646, 0.1128]]),
 tensor([[0.5817, 0.6019, 0.4122],
         [0.4714, 0.9350, 0.8820]]))

In [4]:
torch.eq(a, b)

tensor([[False, False, False],
        [False, False, False]])

In [5]:
torch.equal(a, b)

False

In [6]:
torch.ge(a, b)

tensor([[ True,  True,  True],
        [False, False, False]])

In [7]:
torch.gt(a, b)

tensor([[ True,  True,  True],
        [False, False, False]])

In [8]:
torch.le(a, b)

tensor([[False, False, False],
        [ True,  True,  True]])

In [9]:
torch.lt(a, b)

tensor([[False, False, False],
        [ True,  True,  True]])

In [10]:
torch.ne(a, b)

tensor([[True, True, True],
        [True, True, True]])

In [11]:
a = torch.tensor([1, 4, 4, 3, 5])
torch.sort(a)

torch.return_types.sort(
values=tensor([1, 3, 4, 4, 5]),
indices=tensor([0, 3, 1, 2, 4]))

In [12]:
torch.argsort(a)

tensor([0, 3, 1, 2, 4])

In [13]:
a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
a.shape

torch.Size([2, 5])

In [18]:
torch.sort(a, dim=0, descending=False)

torch.return_types.sort(
values=tensor([[1, 3, 1, 3, 5],
        [2, 4, 4, 3, 5]]),
indices=tensor([[0, 1, 1, 0, 0],
        [1, 0, 0, 1, 1]]))

In [19]:
a = torch.tensor([[2, 4, 3, 1, 5],
                  [2, 3, 5, 1, 4]])
a.shape

torch.Size([2, 5])

In [20]:
torch.topk(a, k=2, dim=0)

torch.return_types.topk(
values=tensor([[2, 4, 5, 1, 5],
        [2, 3, 3, 1, 4]]),
indices=tensor([[0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1]]))

In [21]:
torch.topk(a, k=2, dim=1)

torch.return_types.topk(
values=tensor([[5, 4],
        [5, 4]]),
indices=tensor([[4, 1],
        [2, 4]]))

In [22]:
torch.kthvalue(a,k=2,dim=0)

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))

In [23]:
torch.kthvalue(a,k=2,dim=1)

torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))

In [24]:
a = torch.rand(2,3)
a

tensor([[0.6212, 0.2385, 0.1512],
        [0.4301, 0.5179, 0.3214]])

In [25]:
torch.isfinite(a)

tensor([[True, True, True],
        [True, True, True]])

In [26]:
torch.isfinite(a/0)

tensor([[False, False, False],
        [False, False, False]])

In [27]:
torch.isinf(a/0)

tensor([[True, True, True],
        [True, True, True]])

In [28]:
torch.isnan(a)

tensor([[False, False, False],
        [False, False, False]])