In [1]:
import torch

In [2]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
a, b

(tensor([[0.1715, 0.0107, 0.2621],
         [0.9330, 0.2390, 0.3312]]),
 tensor([[0.5373, 0.2787, 0.8681],
         [0.5262, 0.2434, 0.1359]]))

In [3]:
a + b

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [4]:
a.add(b)

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [5]:
torch.add(a, b)

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [6]:
a, b

(tensor([[0.1715, 0.0107, 0.2621],
         [0.9330, 0.2390, 0.3312]]),
 tensor([[0.5373, 0.2787, 0.8681],
         [0.5262, 0.2434, 0.1359]]))

In [8]:
a.add_(b)  # 加入_后会改变a的值
a, b

(tensor([[1.2460, 0.5680, 1.9982],
         [1.9854, 0.7258, 0.6030]]),
 tensor([[0.5373, 0.2787, 0.8681],
         [0.5262, 0.2434, 0.1359]]))

In [9]:
# sub
a - b

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [10]:
torch.sub(a, b)

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [11]:
a.sub(b)

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [12]:
a.sub_(b)

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [13]:
a

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [14]:
# mul
a * b

tensor([[0.3808, 0.0806, 0.9811],
        [0.7678, 0.1174, 0.0635]])

In [15]:
torch.mul(a, b)

tensor([[0.3808, 0.0806, 0.9811],
        [0.7678, 0.1174, 0.0635]])

In [16]:
a.mul(b)

tensor([[0.3808, 0.0806, 0.9811],
        [0.7678, 0.1174, 0.0635]])

In [17]:
a.mul_(b)
a

tensor([[0.3808, 0.0806, 0.9811],
        [0.7678, 0.1174, 0.0635]])

In [18]:
# div
a / b

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [19]:
torch.div(a, b)

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [20]:
a.div(b)

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [21]:
a.div_(b)
a

tensor([[0.7087, 0.2893, 1.1302],
        [1.4592, 0.4824, 0.4671]])

In [22]:
# matmul
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [23]:
a @ b

tensor([[1., 1.],
        [1., 1.]])

In [28]:
a.matmul(b)

tensor([[1., 1.],
        [1., 1.]])

In [31]:
a.mm(b)

tensor([[1., 1.],
        [1., 1.]])

In [29]:
torch.matmul(a,b)

tensor([[1., 1.],
        [1., 1.]])

In [30]:
torch.mm(a,b)

tensor([[1., 1.],
        [1., 1.]])

In [32]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)

In [35]:
c = a @ b
c.shape

torch.Size([1, 2, 3, 3])

In [38]:
a.matmul(b).shape

torch.Size([1, 2, 3, 3])

In [40]:
torch.matmul(a,b).shape

torch.Size([1, 2, 3, 3])

In [41]:
# pow
a = torch.tensor([1,2])
torch.pow(a,3)

tensor([1, 8])

In [42]:
a**3

tensor([1, 8])

In [43]:
a.pow(3)

tensor([1, 8])

In [44]:
a.pow_(3)
a

tensor([1, 8])

In [46]:
# exp
a = torch.tensor([1,2],dtype=torch.float32)
torch.exp(a)

tensor([2.7183, 7.3891])

In [47]:
a.exp()

tensor([2.7183, 7.3891])

In [48]:
torch.exp_(a)
a

tensor([2.7183, 7.3891])

In [49]:
a.exp_()
a

tensor([  15.1543, 1618.1781])

In [60]:
# log
a = torch.tensor([10,20],dtype=torch.float32)
torch.log(a)

tensor([2.3026, 2.9957])

In [61]:
a.log()

tensor([2.3026, 2.9957])

In [62]:
torch.log_(a)

tensor([2.3026, 2.9957])

In [63]:
a.log_()

tensor([0.8340, 1.0972])

In [64]:
# sqrt
torch.sqrt(a)

tensor([0.9133, 1.0475])

In [65]:
torch.sqrt_(a)

tensor([0.9133, 1.0475])

In [66]:
a.sqrt()

tensor([0.9556, 1.0235])

In [67]:
a.sqrt_()
a

tensor([0.9556, 1.0235])