# 广播机制

满足两个条件
- 每个张量至少有一个维度
- 满足右对齐

In [1]:
import torch

In [17]:
a = torch.rand(2, 3)
b = torch.rand(3)
a, b

(tensor([[0.9883, 0.8832, 0.3638],
         [0.9086, 0.4899, 0.9018]]),
 tensor([0.4012, 0.4448, 0.4226]))

In [18]:
c = a + b
c

tensor([[1.3894, 1.3280, 0.7864],
        [1.3097, 0.9347, 1.3243]])

In [19]:
a = torch.rand(2, 4, 1, 3)
b = torch.rand(4, 2, 3)

In [20]:
c = a + b
c.shape

torch.Size([2, 4, 2, 3])