# 统计学方法

In [1]:
import torch

In [3]:
a = torch.rand(2, 2)
a

tensor([[0.8090, 0.7053],
        [0.0772, 0.1939]])

In [4]:
torch.mean(a)

tensor(0.4464)

In [6]:
torch.sum(a)

tensor(1.7854)

In [7]:
torch.prod(a)

tensor(0.0085)

In [8]:
torch.mean(a, dim=0)

tensor([0.4431, 0.4496])

In [9]:
torch.sum(a, dim=0)

tensor([0.8862, 0.8993])

In [10]:
torch.prod(a, dim=0)

tensor([0.0624, 0.1368])

In [11]:
torch.argmax(a, dim=0)

tensor([0, 0])

In [12]:
torch.argmin(a, dim=0)

tensor([1, 1])

In [13]:
torch.std(a)

tensor(0.3645)

In [14]:
torch.var(a)

tensor(0.1329)

In [15]:
torch.median(a)

tensor(0.1939)

In [16]:
torch.mode(a)

torch.return_types.mode(
values=tensor([0.7053, 0.0772]),
indices=tensor([1, 0]))

In [18]:
a = torch.rand(2, 2) * 10
a

tensor([[7.2041, 9.6314],
        [9.7927, 6.1809]])

In [19]:
torch.histc(a, 6, 0, 0)

tensor([1., 1., 0., 0., 0., 2.])

In [21]:
a = torch.randint(0,10,[10])
a

tensor([2, 8, 6, 8, 2, 9, 2, 1, 1, 8])

In [22]:
torch.bincount(a)

tensor([0, 2, 3, 0, 0, 0, 1, 0, 3, 1])