In [1]:
import torch

In [3]:
dev = torch.device("cpu")

In [5]:
a = torch.tensor([2,2],device=dev)
a

tensor([2, 2])


In [8]:
dev = torch.device("cuda")
a = torch.tensor([2,2],dtype=torch.float32,device=dev)
a

tensor([2., 2.], device='cuda:0')

In [11]:
i = torch.tensor([[0,1,2],[0,1,2]])
v = torch.tensor([1,2,3])
a = torch.sparse_coo_tensor(i,v,(4,4),device=dev)\
    .to_dense() # 转换为稠密矩阵
a

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 0]], device='cuda:0')