In [1]:
import torch

In [2]:
a = torch.Tensor([[1,2],[3,4]])
a

tensor([[1., 2.],
        [3., 4.]])

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
a = torch.Tensor(2,3)
a,a.type()

(tensor([[0.0000e+00, 1.8750e+00, 8.3454e-10],
         [1.6822e-04, 4.3684e-05, 2.7298e-06]]),
 'torch.FloatTensor')

In [5]:
a = torch.ones(2,2)
a,a.type()

(tensor([[1., 1.],
         [1., 1.]]),
 'torch.FloatTensor')

In [6]:
a = torch.eye(2,2)
a,a.type()

(tensor([[1., 0.],
         [0., 1.]]),
 'torch.FloatTensor')

In [7]:
a = torch.zeros(2,2)
a,a.type()

(tensor([[0., 0.],
         [0., 0.]]),
 'torch.FloatTensor')

In [9]:
a = torch.zeros_like(a)
a,a.type()

(tensor([[0., 0.],
         [0., 0.]]),
 'torch.FloatTensor')

In [10]:
a = torch.rand(2,4)
a,a.type()

(tensor([[0.6040, 0.1602, 0.5678, 0.8387],
         [0.1780, 0.8238, 0.0737, 0.9234]]),
 'torch.FloatTensor')

In [11]:
a = torch.normal(mean=0.0,std=torch.rand(5))
a,a.type()

(tensor([-0.0971,  0.3667, -0.4675, -1.2578, -0.0595]), 'torch.FloatTensor')

In [12]:
a = torch.arange(0,10,1)
a,a.type()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'torch.LongTensor')

In [13]:
a = torch.linspace(2,10,3)
a,a.type()

(tensor([ 2.,  6., 10.]), 'torch.FloatTensor')

In [14]:
a = torch.randperm(10)
a,a.type()

(tensor([2, 0, 4, 3, 7, 8, 1, 9, 5, 6]), 'torch.LongTensor')

In [15]:
import numpy as np

In [17]:
a = np.array([[1,2],[2,3]])
a

array([[1, 2],
       [2, 3]])