# 三角函数

In [1]:
import torch

In [2]:
a = torch.rand(2,3)
b = torch.cos(a)

In [4]:
a,b

(tensor([[0.2803, 0.9397, 0.0158],
         [0.5186, 0.4203, 0.9109]]),
 tensor([[0.9610, 0.5900, 0.9999],
         [0.8685, 0.9130, 0.6131]]))

In [5]:
a = torch.zeros(2,3)
b = torch.cos(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
b = torch.cosh(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])